services:
  api:
    build: ./backend
    env_file:
      - ./.env
    environment:
      JWT_SECRET: "${JWT_SECRET:?JWT_SECRET not set}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      DATABASE_URL: "${DATABASE_URL:-sqlite:///./data/hids.db}"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backend/app:/app/app
    ports:
      - "8000:8000"


  # future front-end or other services go here...
