services:
  api:
    build: ./backend
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backend/app:/app/app
    ports:
      - "8000:8000"


  # future front-end or other services go here...
